<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="InventoryAgg\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\0_Framework\0_Framework\0_Framework.csproj" />
    <ProjectReference Include="..\..\IM.Application\InventoryManagement.Application.Contract\InventoryManagement.Application.Contract.csproj" />
  </ItemGroup>

</Project>

