<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCaching.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization.Policy" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Core" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\01_LampShadeQuery\01_LampShadeQuery.csproj" />
  </ItemGroup>

</Project>
