<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Cart\" />
    <Folder Include="Order\" />
    <Folder Include="Slide\" />
    <Folder Include="ProductPicture\" />
    <Folder Include="Product\" />
    <Folder Include="ProductCategory\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SM.Domain\ShopManagement.Domain\ShopManagement.Domain.csproj" />
    <ProjectReference Include="..\ShopManagement.Application.Contract\ShopManagement.Application.Contract.csproj" />
  </ItemGroup>

</Project>

