<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="A.CustomerDiscount\" />
    <Folder Include="A.ColleagueDiscount\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DM.Domain\DiscountManagement.Domain\DiscountManagement.Domain.csproj" />
    <ProjectReference Include="..\DIscountManagement.Application.Contract\DiscountManagement.Application.Contract.csproj" />
  </ItemGroup>

</Project>
