<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
    <Folder Include="Repository\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\AccountManagement\AM.Infrustructure\AccountManagement.Infrastructure.EFCore\AccountManagement.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\..\..\Shopmanagement\SM.Infrastructure\ShopManagement.Infrastructure.EFCore\ShopManagement.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\..\IM.Domain\InventoryManagement.Domain\InventoryManagement.Domain.csproj" />
  </ItemGroup>

</Project>

